// Bundles the server code (supabase/server with @quickbite/core and
// @quickbite/server) into supabase/functions/_shared/server.js, so the Deno
// Edge Functions run exactly the order and payment code the other backends
// run. Web-standard APIs only, so the bundle targets no particular platform.
import { build } from 'esbuild';

await build({
  entryPoints: ['server/index.ts'],
  outfile: 'functions/_shared/server.js',
  bundle: true,
  platform: 'neutral',
  mainFields: ['module', 'main'],
  conditions: ['import', 'default'],
  target: 'es2022',
  format: 'esm',
  // Only a type is imported from postgres.js; the functions import the driver themselves.
  external: ['postgres'],
  banner: { js: '// Generated by supabase/build.mjs from supabase/server. Do not edit.' },
  logLevel: 'info',
});
