# Runs before Claude edits a file. Claude Code sends details about the edit
# as JSON on "standard input". We read it and decide: allow or block.
import json
import posixpath
import sys

data = json.load(sys.stdin)
tool_input = data.get("tool_input", {})

# Most edit tools call the path "file_path"; notebook edits call it "notebook_path".
path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""

# Windows paths use "\", others use "/". Make them all "/", lowercase, and
# tidy up things like "a/../b" so tricks can't sneak past us.
clean = posixpath.normpath(path.replace("\\", "/")).lower()
parts = clean.split("/")  # e.g. ["", "proj", ".venv", "x.py"]
name = parts[-1]          # the file name on its own

reason = None
if name == "habits.db":
    reason = "habits.db is the real database. Editing it by hand could corrupt it or erase user data."
elif name == ".env" or name.startswith(".env.") or name.endswith(".env"):
    reason = ".env files hold secrets and settings, so they must not be changed automatically."
elif ".venv" in parts:
    reason = ".venv/ is generated by pip. Edit requirements.txt and reinstall instead."

if reason:
    # Printing this JSON tells Claude Code to deny the edit and shows the reason.
    print(json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "deny",
        "permissionDecisionReason": f"Blocked edit to {path}: {reason}",
    }}))
# If we print nothing, the edit is allowed.
